repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: eslint --no-warn-ignored
        language: node
        additional_dependencies:
          - eslint@^9
          - eslint-plugin-html@^8
          - globals@^15
          - "@eslint/js@^9"
        types_or: [html, javascript]
        exclude: '\.min\.js$'
        pass_filenames: true
